[binance]
API_KEY = "YuvuoQ4CTmPVDTioFAyUcGYZweWFC5SRVpe4uCDOVGX72sph2j2XCEGZT0aVpgP9"
API_SECRET = "jsZ6DAd5aYdOrqCoKg8Fnlkf5z5jxGmIiUT9gcZU4Go0VPEnk3FzxWwsmVnvKkH9"

[email]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = "arnaudndamukunda@gmail.com"
SMTP_PASSWORD = "irdt huud yupd mhsg"
